packages:
  - "shared"
  - "file-index"
  - "image-classifier"
  - "img-search"
  - "img-val"
  - "img-cleanup"
  - "tag-translator"

allowBuilds:
  blake3: true
  esbuild: true

minimumReleaseAgeExclude:
  - zod@4.5.4
